### ISSUE TITLE
Deployment to Azure fails "Changes commited to remote repo but deployment to website failed"

### ISSUE THREAD

**Issue by jkd65** [XervoIO/demeteorizer#269]
Running `git push remotename master` gives...
```
Counting objects: 10085, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9495/9495), done.
Writing objects: 100% (10085/10085), 12.79 MiB | 1.22 MiB/s, done.
Total 10085 (delta 2148), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: ..........................................................................
remote: Deployment failed
remote: Error - Changes committed to remote repository but deployment to website failed.
```

The KUDU Deployment log gives this error

```
Failed to stat file 'D:/home/site/repository/programs/server/npm/node_modules/meteor/jamesfebin_azure-blob-upload/node_modules/azure-storage/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/test/integration/test-delayed-http-upload.js': The data area passed to a system call is too small.
```

**Comment by fiveisprime** [comment]
I'd recommend using web apps for Linux and deploying your Meteor apps using a custom image over attempting to deploy to a Windows worker with Demeteorizer.

Find a good base image then build the image with your app sourced in. Push that image to docker hub then create a Linux web app and specify the `-i` flag with the path to your image.

```sh
# Setup a group and plan that supports Linux VMs
$ az group create --name meteor -l westus
$ appservice plan create --name meteor-plan -g meteor --is-linux
# Specify the image with `-i`, you can change this in the dashboard later
$ az webapp create --name my-meteor-app-155 -g meteor -p meteor-plan -i <dockerhub username/image>
```

You can do the docker build/push from VS Code using the docker extension if you aren't super familiar with docker.

**Comment by DanceParty** [comment]
Thanks @fiveisprime, I amy try this out sometime, but I fixed the issue I was having by running rm -rf ./ in all of the added folders through the KUDU console.

**Comment by karndeepsingh** [comment]
Hey @DanceParty  I have the same issue while deploying an Image Classification app build using Python on the Azuer Api App service. I tried to deploy it with git commands but in the end it showed the same error as you have mentioned. Please can you help me to rectify the same error like how you did it for yourself?

Thankyou

**Comment by babumushay** [comment]
@karndeepsingh did you found solution to your problem if yes do tell as i am facing similar issue

**Comment by Ismailfaris** [comment]
You pushed a local branch that doesn't match the app deployment branch on 'azure'.	Verify that current branch is master. To change the default branch, use DEPLOYMENT_BRANCH application setting (see https://docs.microsoft.com/en-us/azure/app-service/deploy-local-git?tabs=cli#change-deployment-branch).
